services:
  app:
    build:
      context: .
    image: chat-hub-app:latest # Change to your desired tag
    container_name: chat-hub-app # Change to your desired container name
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code # Change to your project directory
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine # Change to your desired PostgreSQL version
    container_name: chat-hub-db # Change to your desired container name
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost -p 5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Change to your desired PostgreSQL port

volumes:
  postgres_data:
